<?php

/*
 * Copyright (C) 2014 Nikolai Neff <admin@flatplane.de>.
 *
 * This file is part of Flatplane.
 *
 * Flatplane is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Flatplane is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Flatplane.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace de\flatplane\documentElements;

use de\flatplane\interfaces\DocumentElementInterface;
use de\flatplane\utilities\PDF;
use RuntimeException;
use TCPDF;

//todo: formattierungsobjekte: newline, newpage, (h/v-space), clearpage?

//todo: complete documentation!
//todo: methoden sortieren


/**
 * Abstract class for all page elements like sections, text, images, formulas, ...
 * Provides basic common functionality.
 * @author Nikolai Neff <admin@flatplane.de>
 */
abstract class AbstractDocumentContentElement implements DocumentElementInterface
{
    //import functionality horizontally from traits to reduce code length
    use traits\ContentFunctions;
    use traits\NumberingFunctions;
    use traits\StyleFunctions;

    /**
     * @var DocumentElementInterface
     *  Contains a reference to the parent DocumentElement instance
     */
    protected $parent = null;

    /**
     * @var int
     *  type of the element
     */
    protected $type = 'PageElement';

    /**
     * @var bool
     *  defines if the element will recieve its own number
     */
    protected $enumerate = true;

    /**
     * @var string
     *  alternative (shorter) title to be used in lists for this element
     */
    protected $altTitle = '';

    /**
     * @var string
     *  title of the element
     */
    protected $title = '';

    /**
     * @var bool
     *  defines if the element will be displayed in autogenerated lists
     */
    protected $showInList = true;

    /**
     * @var mixed
     *  use a bool to completely allow/disallow subcontent for the element or
     *  define allowed types as array values: e.g. ['section', 'formula']
     *  todo: fix/use me?
     */
    protected $allowSubContent = true;

    /**
     * @var bool
     *  indicates if the element can be split across multiple pages
     */
    protected $isSplitable = false;

    /**
     * @var string
     *  name to identify the element in references
     *  //todo: unique?
     */
    protected $label = '';

    /**
     * @var string
     *  Number of the page this element gets printed on. If the element spans
     *  multiple pages, then this number references the first occurrence.
     */
    protected $page;

    /**
     * @var int
     *  todo: doc
     */
    protected $linearPage;

    /**
     * @var string
     *  identifier used to separate different pagegroups
     */
    protected $pageGroup = 'default';

    /**
     * @var array
     *  defines the elements margins in user-units. Standard keys are:
     *  'top', 'bottom', 'left', 'right'. Subclasses might define their own keys.
     *  If any of those are undefined, the value of the key 'default' is used.
     */
    protected $margins = ['default' => 0];

//    /**
//     * @var array
//     *  defines the elements paddings in user-units. Standard keys are:
//     *  'top', 'bottom', 'left', 'right'. Subclasses might define their own keys.
//     *  If any of those are undefined, the value of the key 'default' is used.
//     */
//    protected $paddings = ['default' => 0];

    protected $hyphenate = true;

    /**
     * @var int
     *  internal link identifier retured by TCPDF::AddLink()
     * @see TCPDF::AddLink()
     * @see TCPDF::SetLink()
     */
    protected $link;

    /**
     * This method is called on creating a new element.
     * @param array $config
     *  Array containing key=>value pairs wich overwrite the default properties.
     *  e.g.: $config = ['enumerate' => false] will disable numbering for the
     *  created instance
     */
    public function __construct(array $config)
    {
        $this->setConfig($config);
    }

    /**
     * @param array $config
     *  Array containing key=>value pairs wich overwrite the default properties.
     *  e.g.: $config = ['enumerate' => false] will disable numbering for the
     *  created instance
     */
    public function setConfig(array $config)
    {
        $this->testNoParent();
        foreach ($config as $key => $setting) {
            $name = 'set'.ucfirst($key);
            if (method_exists($this, $name)) {
                $this->$name($setting);
            } else {
                trigger_error(
                    "$key is not a valid Configuration option, ignoring",
                    E_USER_NOTICE
                );
            }
        }
    }

    public function __toString()
    {
        return (string) $this->getTitle();
    }

    /**
     * Sets the parent to an instance implementing DocumentElementInterface
     * @param DocumentElementInterface $parent
     */
    public function setParent(DocumentElementInterface $parent)
    {
        $this->parent = $parent;
    }

    /**
     * @return DocumentElementInterface
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @return PDF
     */
    public function getPDF()
    {
        return $this->toRoot()->getPDF();
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function getType()
    {
        return $this->type;
    }

    /**
     * @return mixed
     */
    public function getPage()
    {
        if (empty($this->page)) {
            $this->page = str_repeat(
                $this->toRoot()->getUnresolvedReferenceMarker(),
                $this->toRoot()->getAssumedPageNumberWidth()
            );
        }
        return $this->page;
    }

    /**
     * @param mixed $page
     */
    public function setPage($page)
    {
        $this->page = $page;
    }

    /**
     * @throws RuntimeException
     */
    protected function testNoParent()
    {
        if ($this->getParent() !== null) {
            throw new RuntimeException(
                "The configuration can't be changed after setting the parent"
            );
        }
    }

    /**
     * @param bool $enumerate
     */
    public function setEnumerate($enumerate)
    {
        if ($this->getParent() !== null) {
            trigger_error(
                'setEnumerate() should not be called after adding the element '
                .'as content. Doing so might lead to erratic behavior regarding'
                .'element numbering. Please use the $settings array in the '
                .'constructor instead',
                E_USER_NOTICE
            ) ;
        }
        $this->enumerate = (bool) $enumerate;
    }

    /**
     * @param bool $showInList
     */
    public function setShowInList($showInList)
    {
        $this->showInList = (bool) $showInList;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     *
     * @param array $margins
     *  keys: 'top', 'bottom', 'left', 'right'
     *  values: (numeric) margin amount (user units)
     */
    public function setMargins(array $margins)
    {
        $this->margins = array_merge($this->margins, $margins);
    }

    /**
     * @return bool
     */
    public function getEnumerate()
    {
        return $this->enumerate;
    }

    /**
     * @return bool
     */
    public function getShowInList()
    {
        return $this->showInList;
    }

    /**
     * @return mixed
     */
    public function getAllowSubContent()
    {
        return $this->allowSubContent;
    }

    /**
     * @return bool
     */
    public function getIsSplitable()
    {
        return $this->isSplitable;
    }

    /**
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * set a label as identifier for references
     * @param string $label
     */
    public function setLabel($label)
    {
        $this->label = $label;
        if (!in_array($this, $this->toRoot()->getLabels())) {
            $this->toRoot()->addLabel($this);
        }
    }


    public function setFillColor(array $fillColor)
    {
        $this->fillColor = $fillColor;
    }

    public function getMargins($key = null)
    {
        if ($key !== null && isset($this->margins[$key])) {
            return $this->margins[$key];
        } else {
            return $this->margins['default'];
        }
    }

    public function getPaddings($key = null)
    {
        if ($key !== null && isset($this->paddings[$key])) {
            return $this->paddings[$key];
        } else {
            return $this->paddings['default'];
        }
    }

    public function setAltTitle($altTitle)
    {
        $this->altTitle = $altTitle;
    }

    public function getAltTitle()
    {
        if (empty($this->altTitle)) {
            return $this->getTitle();
        } else {
            return $this->altTitle;
        }
    }

    /**
     * todo: doc
     * @return array
     *  Keys: pageWidth, textWidth, pageHeight, textHeight
     */
    public function getPageMeasurements()
    {
        $pdf = $this->getPDF();

        $pageWidth = $pdf->getPageWidth();
        $textWidth = $pageWidth - $pdf->getMargins()['left']
                                - $pdf->getMargins()['right'];

        $pageHeight = $pdf->getPageHeight();
        //margin bottom includes footnotes margin
        $textHeight = $pageHeight - $pdf->getMargins()['top']
                                  - $pdf->getMargins()['bottom'];

        return ['pageWidth' => $pageWidth,
                'textWidth' => $textWidth,
                'pageHeight' => $pageHeight,
                'textHeight' => $textHeight];
    }

    /**
     *
     * @return bool
     */
    public function getHyphenate()
    {
        return $this->hyphenate;
    }

    /**
     *
     * @param bool $hyphenate
     */
    public function setHyphenate($hyphenate)
    {
        $this->hyphenate = $hyphenate;
    }

    /**
     * todo: doc
     */
    public function hyphenateTitle()
    {
        if ($this->getHyphenate()) {
            if ($this->getAltTitle() !== $this->getTitle()) {
                $this->setAltTitle(
                    $this->toRoot()->hypenateText($this->getAltTitle())
                );
            }
            $this->setTitle($this->toRoot()->hypenateText($this->getTitle()));
        }
    }

    /**
     * @return array
     */
    public function getSize($startYposition = null)
    {
        //todo: return width?
        $pdf = $this->getPDF();
        $pdf->startMeasurement($startYposition);
        $this->generateOutput();
        return $pdf->endMeasurement();
    }

    public function getLinearPage()
    {
        return $this->linearPage;
    }

    public function setLinearPage($linearPage)
    {
        $this->linearPage = $linearPage;
    }

    /**
     * todo: doc
     * @param string $source
     * @param string $extras
     * @return string
     */
    public function cite($source, $extras = '')
    {
        //todo: remove cite prefix/postfix, own style for Cite!
        $sourceList = $this->toRoot()->getSources();
        if (array_key_exists($source, $sourceList)) {
            $citeStyle = $this->toRoot()->getCitationStyle();
            //$cite = $citeStyle['prefix'];
            $cite = '';
            $cite .= $sourceList[$source]->getFormattedNumbers();
            $sourceList[$source]->setParent($this);
            if (!empty($extras)) {
                $cite .= $citeStyle['separator'].' '.$extras;
            }
            //$cite .= $citeStyle['postfix'];
        } else {
            trigger_error(
                'Source "'.$source.'" for citation not found',
                E_USER_NOTICE
            );
            $cite = '[??]'; //todo: use assumption settings
        }
        return $cite;
    }

    public function getLink()
    {
        return $this->link;
    }

    public function setLink($link)
    {
        $this->link = $link;
    }

    public function getPageGroup()
    {
        return $this->pageGroup;
    }

    public function setPageGroup($pageGroup)
    {
        $this->pageGroup = $pageGroup;
    }
}
