<?php

/*
 * Copyright (C) 2014 Nikolai Neff <admin@flatplane.de>.
 *
 * This file is part of Flatplane.
 *
 * Flatplane is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or(at your option) any later version.
 *
 * Flatplane is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Flatplane.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace de\flatplane\documentContents;

use de\flatplane\interfaces\DocumentElementInterface;

//todo: formattierungsobjekte: newline, newpage, (h/v-space), clearpage?

//todo: complete documentation!
//todo: methoden sortieren

/**
 * Abstract class for all page elements like sections, text, images, formulas, ...
 * Provides basic common functionality.
 * @author Nikolai Neff <admin@flatplane.de>
 */
abstract class AbstractDocumentContentElement implements DocumentElementInterface
{
    //import functionality horizontally from traits to reduce code length
    use traits\ContentFunctions;
    use traits\NumberingFunctions;

    /**
     * @var DocumentElementInterface
     *  Contains a reference to the parent DocumentElement instance
     */
    protected $parent = null;

    /**
     * @var int
     *  type of the element
     */
    protected $type = 'PageElement';

    /**
     * @var bool
     *  defines if the element will recieve its own number
     */
    protected $enumerate = true;

    /**
     * @var string
     *  title of the element
     */
    protected $title = '';

    /**
     * @var bool
     *  defines if the element will be displayed in autogenerated lists
     */
    protected $showInList = true;

    /**
     * @var mixed
     *  use a bool to completely allow/disallow subcontent for the element or
     *  define allowed types as array values: e.g. ['section', 'formula']
     */
    protected $allowSubContent = true;

    /**
     * @var bool
     *  indicates if the element can be split across multiple pages
     */
    protected $isSplitable = false;

    /**
     * @var string
     *  name to identify the element in references
     *  //todo: unique?
     */
    protected $label = '';

    /**
     * @var array
     *  defines the elements margins in user-units. Valid keys are:
     *  'top', 'bottom', 'left', 'right'. If any of those is undefined, the
     *  value of the key 'default' is used.
     */
    protected $margins = ['default' => 0];

    /**
     * @var array
     *  defines the elements paddings in user-units. Valid keys are:
     *  'top', 'bottom', 'left', 'right'. If any of those is undefined, the
     *  value of the key 'default' is used.
     */
    protected $paddings = ['default' => 0];

    /**
     * todo: update doc here
     * @var array
     *  defines the elements fontType: use a name of a font definition file or
     *  an identifier from PDF::addFont()
     */
    protected $fontType = ['default' => 'times'];

    /**
     * @var array
     *  possible values: Font size in pt
     */
    protected $fontSize = ['default' => 12];

    /**
     * @var array
     *  possible values: Font variations as strings:
     *  <ul>
     *   <li>(empty): normal</li>
     *   <li>U: underline</li>
     *   <li>D: strikethrough</li>
     *   <li>B: bold</li>
     *   <li>I: italic</li>
     *   <li>O: overline</li>
     *  </ul>
     * The variations can be combined: e.g. 'BIU' (in any order) for
     * bold-italic-underline
     */
    protected $fontStyle = ['default' => ''];

    /**
     * Color used for Text
     * todo: validate doc
     * @var array
     *  possible values:
     *  array containing 1 value (0-255) for grayscale
     *  array containing 3 values (0-255) for RGB colors or
     *  array contining 4 values (0-1) for CMYK colors
     */
    protected $fontColor = ['default' => [0,0,0]];

    /**
     * todo: validate doc
     * Color used for drawings (includes some font-styles like underline)
     * @var array
     *  possible values:
     *  array containing 1 value (0-255) for grayscale
     *  array containing 3 values (0-255) for RGB colors or
     *  array contining 4 values (0-1) for CMYK colors
     */
    protected $drawColor = ['default' => [0,0,0]];

    /**
     * This method is called on creating a new element.
     * @param array $config
     *  Array containing key=>value pairs wich overwrite the default properties.
     *  e.g.: $config = ['enumerate' => false] will disable numbering for the
     *  created instance
     */
    public function __construct(array $config)
    {
        $this->setConfig($config);
    }

    /**
     * @param array $config
     *  Array containing key=>value pairs wich overwrite the default properties.
     *  e.g.: $config = ['enumerate' => false] will disable numbering for the
     *  created instance
     */
    public function setConfig(array $config)
    {
        $this->testNoParent();
        foreach ($config as $key => $setting) {
            $name = 'set'.ucfirst($key);
            if (method_exists($this, $name)) {
                $this->$name($setting);
            } else {
                trigger_error(
                    "$key is not a valid Configuration option, ignoring",
                    E_USER_NOTICE
                );
            }
        }
    }

    /**
     * todo: doc, maybe unneccesary?
     */
    public function __clone()
    {
        $this->parent = null;
    }

    public function __toString()
    {
        return (string) $this->getTitle();
    }

    /**
     * Sets the parent to an instance implementing DocumentElementInterface
     * @param DocumentElementInterface $parent
     */
    public function setParent(DocumentElementInterface $parent)
    {
        $this->parent = $parent;
    }

    /**
     * @return DocumentElementInterface
     */
    public function getParent()
    {
        return $this->parent;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function getType()
    {
        return $this->type;
    }

    public function getPage()
    {
        //todo: fix me
        return '????';
    }

    /**
     * @thros RuntimeException
     */
    protected function testNoParent()
    {
        if ($this->getParent() !== null) {
            throw new RuntimeException(
                "The configuration can't be changed after setting the parent"
            );
        }
    }

    /**
     * @param bool $enumerate
     */
    protected function setEnumerate($enumerate)
    {
        $this->enumerate = (bool) $enumerate;
    }

    /**
     * @param bool $showInList
     */
    protected function setShowInList($showInList)
    {
        $this->showInList = (bool) $showInList;
    }

    protected function setTitle($title)
    {
        $this->title = $title;
    }

    protected function setMargins(array $margins)
    {
        $this->margins = $margins;
    }

    protected function setPaddings(array $paddings)
    {
        $this->paddings = $paddings;
    }

    protected function setFontType(array $fontType)
    {
        $this->fontType = $fontType;
    }

    protected function setFontSize(array $fontSize)
    {
        $this->fontSize = $fontSize;
    }

    protected function setFontStyle(array $fontStyle)
    {
        $this->fontStyle = $fontStyle;
    }

    protected function setFontColor(array $fontColor)
    {
        $this->fontColor = $fontColor;
    }

    protected function setDrawColor(array $drawColor)
    {
        $this->drawColor = $drawColor;
    }

    /**
     * @return bool
     */
    public function getEnumerate()
    {
        return $this->enumerate;
    }

    /**
     * @return bool
     */
    public function getShowInList()
    {
        return $this->showInList;
    }

    /**
     * @return mixed
     */
    public function getAllowSubContent()
    {
        return $this->allowSubContent;
    }

    /**
     * @return bool
     */
    public function getIsSplitable()
    {
        return $this->isSplitable;
    }

    /**
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * set a label as identifier for references
     * @param string $label
     */
    public function setLabel($label)
    {
        $this->label = $label;
    }

    //abstract public function getSize();
}
